### PR TITLE
Pull v0.22 of libgit2sharp

### PR DESCRIPTION
**Pull request by tomcsmith1990**
This pulls in v0.22 of libgit2sharp, not for any particular reason, just to keep up to date.

It [passed on TeamCity](http://buildserver.red-gate.com/viewLog.html?buildId=7276525&tab=buildResultsDiv&buildTypeId=SignedNuGetPackages_RedgateForkOfLibGit2Sharp).

Probably worth testing the package in SOC first to check that the installer/nuget package is correct. I had to pull in TPL as a dependency since we're building for .NET 3.5.

### CODE REVIEW

**Comment by jmbillings** [comment]
Testing this against soc http://buildserver.red-gate.com/project.html?projectId=SqlSourceControl&tab=projectOverview&branch_SqlSourceControl=ul

**Comment by jmbillings** [comment]
Well, I still can't link into the soc folder with this branch, so it's not magically fixed all the out-of-memory problems :(

**Comment by tomcsmith1990** [comment]
Might still be worth merging if it passes all of the SOC tests

**Comment by jmbillings** [comment]
> Might still be worth merging if it passes all of the SOC tests

Possibly - I'll try the same thing on `master` just to check we're not making it worse though...

**Comment by jmbillings** [comment]
All the git tests have passed on this (only problem was an installer test that needs a version updating). Current build of master failed with an out of memory too, so it doesn't look like this is /worse/...

**Pull request merged**
